name: Build Cross-Platform Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile --windowed --add-data "LICENSE.txt;." --add-data "hilfe.md;." --add-data "assets;assets" --name "Classload" --icon=assets/icon.ico tk_main_menue.py
      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: Windows-EXE
          path: dist/*.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install py2app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app
          # pip install pyinstaller

      - name: Clean PyInstaller output
        run: |
          rm -rf build dist *.spec

      - name: Build macOS App with py2app
        run: |
          python setup.py py2app
          

      - name: Zip App Bundle
        run: |
          cd dist
          zip -r Classload-mac.zip Classload.app

      - name: Upload macOS ZIP
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: dist/Classload-mac.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Linux Executable
        run: |
          pyinstaller --onefile --windowed --name "Classload" tk_main_menue.py

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v4
        with:
          name: Linux-Binary
          path: dist/*
