name: Build Cross-Platform Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile --windowed --add-data "LICENSE.txt;." --add-data "README.md;." --add-data "screenshot.png;." --add-data "assets;assets" --name "Classload" --icon=assets/icon.ico tk_main_menue.py
      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: Classload-EXE
          path: dist/*.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Qt via Homebrew
        run: brew install qt

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app pyobjc-core

      - name: Clean previous builds
        run: |
          rm -rf build dist *.spec

      - name: Build macOS .app with py2app
        run: |
          python setup.py py2app

      - name: Create ZIP archive of .app
        run: |
          cd dist
          zip -r Classload-mac.zip Classload.app

      - name: Upload .app ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Classload-mac
          path: dist/Classload-mac.zip


  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Qt WebEngine dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 libxcomposite1 libxrandr2 libxkbcommon0 libx11-xcb1 libxcb1 \
            libxcb-glx0 libxcb-keysyms1 libxcb-image0 libxcb-shm0 libxcb-icccm4 libxcb-sync1 libxcb-xfixes0 \
            libxcb-shape0 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-util1 libglu1-mesa libnss3

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --noconfirm --onefile --windowed \
            --collect-submodules PySide6 \
            --collect-data PySide6 \
            --add-data "LICENSE.txt:." \
            --add-data "README.md:." \
            --add-data "screenshot.png:." \
            --add-data "assets:assets" \
            --name "Classload" \
            --icon=assets/icon.ico \
            tk_main_menue.py

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v4
        with:
          name: Classload-linux
          path: dist/Classload

